# Utiliser une image officielle Python
FROM python:3.9-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers de l'application dans l'image Docker
COPY ./backend /app

# Installer les dépendances Python
RUN pip install --no-cache-dir -r /app/requirements.txt

# Exposer le port sur lequel FastAPI écoute
EXPOSE 8000

# Commande pour exécuter le backend
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
